# Generated by Django 5.0 on 2023-12-31 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0018_remove_product_filter_price_delete_filter_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
